import { Geist, Geist_Mono, EB_Garamond, Roboto, Golos_Text} from "next/font/google";
import "./globals.css";
import NavigationBar from "./navbar/navigationbar";

const golosText = Golos_Text({
  variable: "--font-golos-text",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${ebGaramond.variable} ${golosText.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col bg-neutral-950 text-white">
          <NavigationBar />
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
